trigger:
  - gh-pages

pool:
  vmImage: windows-2019

steps:

  - task: DotNetCoreInstaller@0
    displayName: 'Install .NetCore SDK'
    inputs:
      version: 3.0.100

  - powershell: |
      choco install docfx -y
      docfx docs/docfx.json
    displayName: "docfx build"
